spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mocktestpro
    username: postgres
    password: postgres123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/mocktestpro

server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    com.mocktestpro: DEBUG

keycloak:
  auth-server-url: http://localhost:8180
  realm: mocktestpro
  resource: mocktestpro-backend
  credentials:
    secret: yWdvlRrahuTqDyvWlGt0OaNxBn9FriSQ